### ISSUE TITLE
"Ukedown" markdown for ukebook

### ISSUE THREAD

**Issue by smudgefarrier** [birdcolour/Ukebook#1]
Hi,

I'm suggesting we introduce a simple markdown-esque method for submitting ukulele songs - "Ukedown". Submitting songs in word (or odt) is heavyweight and feature rich, whereas what we really want is the right features to keep transcribed songs readable and simple for all, and to format it easily for different outputs (whether traditional pdf or small screen phones) without requiring submitters to tailor their submissions for all output formats and devices. I expect this to make it simpler for everyone to submit songs, and make tracking of diffs, comments, and alternations easier.

I'm going to start on doing this, might as well get things moving. I'm sharing this to give others visibility, and to see if anything thinks this is a bad idea, has suggestions or better alternatives, etc.

My first milestone is to have a simple javascript convertor for a textarea with css to match the current song book format. It should be mostly copy paste existing songs to port them over. Basic ukedown is something like this (regexp made up just for example):
- ```"\([A-Z][a-z0-9#]*\)"``` is a chord like (C) or (F#sus4), will allow things like (C-G-C) or (Am - Single strum) or (C///). Will automatically add the chord diagrams.
- ```"\[[A-Za-z0-9_]+\]"``` is a label like [intro], will allow things like [intro - repeat 4 times]
- ```"x[0-9]+``` repeats like x2 formatted in bold italics
- ```"^|"``` to draw a box around a stanza (like a chorus to repeat later).
- Not a box but has this, ```"|"``` to indicates barlines.
- Not a chord but matches ```"([A-Za-z0-9_ ]+)``` a second voice

As an example (using a the boxed section because it won't be copy paste able and is a bit different).

```
|[chorus]
|(C) This is a boxed chor(Am)us
|(G) It spans multi(G)ple lines.
```

I expect this to produce html like:

```html
<div class="boxed">
<p>
<span class="label">chorus</span><br />
<span class="chord">C</span> This is a boxed chor<span class="chord">Am</span>us<br />
<span class="chord">G</span> It spans multi<span class="chord">G</span>ple lines.<br />
</p>
</div>
```

With the stylesheet being like this:
```css
.label {
    font-weight:bold;
}

.label:before {
    content: "[";
}

.label:after {
    content: "]";
}

.chord {
    font-weight:bold;
}

.chord:before {
    content: "(";
}

.chord:after {
    content: ")";
}

.boxed {
    border:1px solid black;
    padding-bottom:0.2em;
    margin-top: 1em;
    margin-bottom: 1em;
}

.boxed > p {
    margin-top: 0;
    margin-bottom:1em;
}

.boxed > p:last-child {
    margin-bottom:0;
}
```

Thanks in advance for any feedback,
Mark
